esphome:
  name: esphome-web-c71724
  on_boot:
    priority: 800
    # ...
    then:
      - switch.turn_off: trelay_airzone_salon_chauffage
      - switch.turn_off: trelay_airzone_salon_climatisation
      - switch.turn_off: trelay_airzone_clea_chauffage
      - switch.turn_off: trelay_airzone_clea_climatisation
      - switch.turn_off: trelay_airzone_emie_chauffage
      - switch.turn_off: trelay_airzone_emie_climatisation
      - switch.turn_off: trelay_airzone_parents_chauffage
      - switch.turn_off: trelay_airzone_parents_climatisation

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

substitutions:
  name: "Airzone"
  temperature_sensor_ch_parents: sensor.lumi_baro_zigbee_1_temperature
  temperature_sensor_ch_clea: sensor.chambre_clea_temperature
  temperature_sensor_ch_emie: sensor.chambre_emie_temperature
  #temperature_sensor_salon: ensor.maison_temperature.  #!!!! a remettre apres TEST
  
#virtual for testing purpose
  heater: input_boolean.virtual_heater 
  cooler: input_boolean.virtual_cooler
  temperature_sensor_salon: input_number.fake_one_temp 

sensor:
  - platform: homeassistant
    id: ch_parents_temperature
    entity_id: $temperature_sensor_ch_parents
    internal: true
  - platform: homeassistant
    id: ch_clea_temperature
    entity_id: $temperature_sensor_ch_clea
    internal: true
  - platform: homeassistant
    id: ch_emie_temperature
    entity_id: $temperature_sensor_ch_emie
    internal: true
  - platform: homeassistant
    id: salon_temperature
    entity_id: $temperature_sensor_salon
    internal: true

climate:
##### Thermostat Parents
  - platform: thermostat
    name: $name Parents
    id: trelay_thermostat_parents
    visual:
      min_temperature: 10
      max_temperature: 35
    sensor: ch_parents_temperature
    default_preset: Chauffage                 ### NEW! Use this to set Preset
    on_boot_restore_from: memory              ### Use this to "Restore From Memeory" (A Saved State) OR...
    # on_boot_restore_from: default_preset    ### Use this to set Preset to start on every Boot    
    preset:
      - name: Chauffage
        default_target_temperature_low: 19.5  
        default_target_temperature_high: 20.5
      - name: Climatisation
        default_target_temperature_low: 25.5  
        default_target_temperature_high: 26.5
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              
    min_heating_run_time: 1s              
    min_idle_time: 1s
    cool_action:
      - switch.turn_off: trelay_airzone_parents_chauffage
      - switch.turn_on: trelay_airzone_parents_climatisation
    heat_action:
      - switch.turn_off: trelay_airzone_parents_climatisation
      - switch.turn_on: trelay_airzone_parents_chauffage
    idle_action:
      - switch.turn_off: trelay_airzone_parents_climatisation
      - switch.turn_off: trelay_airzone_parents_chauffage
##### Thermostat Clea
  - platform: thermostat
    name: $name Cléa
    id: trelay_thermostat_clea
    visual:
      min_temperature: 10
      max_temperature: 35
    sensor: ch_clea_temperature
    default_preset: Chauffage                 ### NEW! Use this to set Preset
    on_boot_restore_from: memory              ### Use this to "Restore From Memeory" (A Saved State) OR...
    # on_boot_restore_from: default_preset    ### Use this to set Preset to start on every Boot    
    preset:
      - name: Chauffage
        default_target_temperature_low: 19.5  
        default_target_temperature_high: 20.5
      - name: Climatisation
        default_target_temperature_low: 25.5  
        default_target_temperature_high: 26.5
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              
    min_heating_run_time: 1s              
    min_idle_time: 1s
    cool_action:
      - switch.turn_off: trelay_airzone_clea_chauffage
      - switch.turn_on: trelay_airzone_clea_climatisation
    heat_action:
      - switch.turn_off: trelay_airzone_clea_climatisation
      - switch.turn_on: trelay_airzone_clea_chauffage
    idle_action:
      - switch.turn_off: trelay_airzone_clea_climatisation
      - switch.turn_off: trelay_airzone_clea_chauffage
##### Thermostat Emie
  - platform: thermostat
    name: $name Emie
    id: trelay_thermostat_emie
    visual:
      min_temperature: 10
      max_temperature: 35
    sensor: ch_emie_temperature
    default_preset: Chauffage                 ### NEW! Use this to set Preset
    on_boot_restore_from: memory              ### Use this to "Restore From Memeory" (A Saved State) OR...
    # on_boot_restore_from: default_preset    ### Use this to set Preset to start on every Boot    
    preset:
      - name: Chauffage
        default_target_temperature_low: 19.5  
        default_target_temperature_high: 20.5
      - name: Climatisation
        default_target_temperature_low: 25.5  
        default_target_temperature_high: 26.5
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              
    min_heating_run_time: 1s              
    min_idle_time: 1s
    cool_action:
      - switch.turn_off: trelay_airzone_emie_chauffage
      - switch.turn_on: trelay_airzone_emie_climatisation
    heat_action:
      - switch.turn_off: trelay_airzone_emie_climatisation
      - switch.turn_on: trelay_airzone_emie_chauffage
    idle_action:
      - switch.turn_off: trelay_airzone_emie_climatisation
      - switch.turn_off: trelay_airzone_emie_chauffage
##### Thermostat Salon
  - platform: thermostat
    name: $name Salon
    id: trelay_thermostat_salon
    visual:
      min_temperature: 10
      max_temperature: 35
    sensor: salon_temperature
    default_preset: Chauffage                 ### NEW! Use this to set Preset
    on_boot_restore_from: memory              ### Use this to "Restore From Memeory" (A Saved State) OR...
    # on_boot_restore_from: default_preset    ### Use this to set Preset to start on every Boot    
    preset:
      - name: Chauffage
        default_target_temperature_low: 19.5  
        default_target_temperature_high: 20.5
      - name: Climatisation
        default_target_temperature_low: 25.5  
        default_target_temperature_high: 26.5
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s              
    min_heating_run_time: 1s              
    min_idle_time: 1s
    cool_action:
      - homeassistant.service: ###TEST
          service: homeassistant.turn_on
          data:
            entity_id: $cooler
      - homeassistant.service: ###TEST
          service: homeassistant.turn_off
          data:
            entity_id: $heater
      - switch.turn_off: trelay_airzone_salon_chauffage
      - switch.turn_on: trelay_airzone_salon_climatisation
    heat_action:
      - homeassistant.service: ###TEST
          service: homeassistant.turn_off
          data:
            entity_id: $cooler
      - homeassistant.service: ###TEST
          service: homeassistant.turn_on
          data:
            entity_id: $heater
      - switch.turn_off: trelay_airzone_salon_climatisation
      - switch.turn_on: trelay_airzone_salon_chauffage
    idle_action:
      - homeassistant.service: ###TEST
          service: homeassistant.turn_off
          data:
            entity_id: $cooler
      - homeassistant.service: ###TEST
          service: homeassistant.turn_off
          data:
            entity_id: $heater
      - switch.turn_off: trelay_airzone_salon_climatisation
      - switch.turn_off: trelay_airzone_salon_chauffage




##################switch pour airzone
switch:
  - platform: gpio
    pin: GPIO33
    name: "Airzone Salon Chauffage"
    id: trelay_airzone_salon_chauffage

  - platform: gpio
    pin: GPIO32
    name: "Airzone Salon Climatisation"
    id: trelay_airzone_salon_climatisation

  - platform: gpio
    pin: GPIO13
    name: "Airzone Cléa Chauffage"
    id: trelay_airzone_clea_chauffage

  - platform: gpio
    pin: GPIO12
    name: "Airzone Cléa Climatisation"
    id: trelay_airzone_clea_climatisation

  - platform: gpio
    pin: GPIO21
    name: "Airzone Emie Chauffage"
    id: trelay_airzone_emie_chauffage

  - platform: gpio
    pin: GPIO19
    name: "Airzone Emie Climatisation"
    id: trelay_airzone_emie_climatisation

  - platform: gpio
    pin: GPIO18
    name: "Airzone Parents Chauffage"
    id: trelay_airzone_parents_chauffage

  - platform: gpio
    pin: GPIO5
    name: "Airzone Parents Climatisation"
    id: trelay_airzone_parents_climatisation

captive_portal:
